# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ef1654884d0f2799f409be7187d09619"
name = "store-locator-account"
handle = "store-locator-account-1"
application_url = "https://exactly-communities-temporary-graph.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "customer_read_companies,customer_read_customers,customer_read_locations,customer_read_orders,customer_write_companies,customer_write_customers,customer_write_locations,read_customers,read_orders"

[auth]
redirect_urls = ["https://exactly-communities-temporary-graph.trycloudflare.com/auth/callback", "https://exactly-communities-temporary-graph.trycloudflare.com/auth/shopify/callback", "https://exactly-communities-temporary-graph.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
